####Hurst Exponent

In [ ]:
!pip install pingouin
!pip install statsmodels

In [ ]:
!pip install statsmodels --upgrade

In [ ]:
import numpy as np
import pandas as pd
import pingouin as pg
import statsmodels.stats.multitest as mc


In [ ]:
#compute partial correlation using Spearman's Rank by including age as a covariate at the ROI level

demo = "/content/drive/MyDrive/Year2/demographics_HE_df.xlsx"
demographics_df = pd.read_excel(demo, sheet_name = 'demographics_hurst_HE_df')

pg.partial_corr(data = demographics_df, x = 'malCERQ', y = 'HE_L_aINS', covar = ['Age'], method = 'spearman')


n         r          CI95%     p-val
spearman  50  0.070243  [-0.22, 0.34]  0.631513

In [ ]:
#apply FDR correction to adjust the p values for multiple comparisons across RO1s

HE_BDI = [0.0039, 0.50, 0.98, 0.88, 0.67, 0.48, 0.34, 0.98, 0.14, 0.22]
HE_adapCERQ = [0.0044, 0.80, 0.87, 0.28, 0.33, 0.63, 0.14, 0.54, 0.92, 0.74]
HE_maladapCERQ = [0.0075, 0.94, 0.68, 0.76, 0.59, 0.40, 0.68, 0.84, 0.34, 0.63]
mc.fdrcorrection(HE_maladapCERQ, alpha = 0.05, method = 'i', is_sorted = False)


(array([False, False, False, False, False, False, False, False, False,
        False]),
 array([0.075     , 0.94      , 0.93333333, 0.93333333, 0.93333333,
        0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.93333333]))

In [ ]:
#compute partial correlation using Spearman's Rank by including age as a covariate at the network level

demo = "/content/drive/MyDrive/Year2/demographics_HE_df.xlsx"
demographics_df = pd.read_excel(demo, sheet_name = 'demographics_hurst_networks_HE')

pg.partial_corr(data = demographics_df, x = 'malCERQ', y = 'LIM', covar = ['Age'], method = 'spearman')


n         r         CI95%     p-val
spearman  50 -0.130112  [-0.4, 0.16]  0.372894

In [ ]:
#apply FDR correction to adjust the p values for multiple comparisons across networks

HE_BDI = [0.0019, 0.13, 0.83, 0.93, 0.28, 0.98, 0.54, 0.16]
HE_adapCERQ = [0.022, 0.32, 0.44, 0.71, 0.16, 0.65, 0.80, 0.22]
HE_maladapCERQ = [0.0071, 0.28, 0.65, 0.69, 0.73, 0.37, 0.39, 0.076]
mc.fdrcorrection(HE_maladapCERQ, alpha = 0.05, method = 'i', is_sorted = False)


(array([False, False, False, False, False, False, False, False]),
 array([0.0568, 0.624 , 0.73  , 0.73  , 0.73  , 0.624 , 0.624 , 0.304 ]))